analytics.onpremise.enable=true
onpremise.email="jisha.thomas@katalon.com"
onpremise.password="zuUhTv5aam/40+5WQZhjlQ\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1489519,\\"accountUuid\\"\:\\"0a7a6246-1c43-471c-a311-a40430bffdc1\\",\\"id\\"\:2636426,\\"name\\"\:\\"Jisha_TOG3\\",\\"role\\"\:\\"USER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false,\\"domain\\"\:\\"success-katalon-g2\\"}"
analytics.onpremise.server="https\://testops.katalon.io"
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 2596814,\\n  \\"name\\"\: \\"Onboarding\\",\\n  \\"teamId\\"\: 2573926,\\n  \\"organizationId\\"\: 2636426,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2573926\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
